/**:
  ros__parameters:
    pose_link: sucker_link
    tool_reference_link: sucker_link
    tool_to_ik_offset_x: 0.1112
    tool_to_ik_offset_y: -0.0235
    tool_to_ik_offset_z: 0.0
    discrete_lift_mode: true
    execute_with_controller: true
    controller_action_name: /mobile_arm_controller/follow_joint_trajectory
    auto_start_on_target: true
    auto_accept_base_arrival: true
    skip_base_execution: true
    pump_command_topic: /medipick/task/pump_command
    suction_state_topic: /medipick/hardware/suction_state
    pump_after_insert: true
    require_suction_for_success: false
    suction_wait_timeout: 1.5
