rgbd_odometry:
  ros__parameters:
    frame_id: base_link
    odom_frame_id: world
    publish_tf: false
    wait_imu_to_init: true
    approx_sync: true
    approx_sync_max_interval: 0.03
    topic_queue_size: 30
    sync_queue_size: 30
    subscribe_rgbd: false
    subscribe_rgb: true
    subscribe_depth: true
    subscribe_odom_info: false
    Vis/MinInliers: "15"
    Odom/Strategy: "0"
    Odom/GuessMotion: "true"
    Odom/Holonomic: "true"
    OdomF2M/MaxSize: "1000"

rtabmap:
  ros__parameters:
    frame_id: base_link
    odom_frame_id: world
    map_frame_id: map
    publish_tf: true
    wait_imu_to_init: true
    approx_sync: true
    approx_sync_max_interval: 0.03
    topic_queue_size: 30
    sync_queue_size: 30
    subscribe_rgbd: false
    subscribe_rgb: true
    subscribe_depth: true
    subscribe_scan: false
    subscribe_scan_cloud: false
    subscribe_odom_info: false
    Reg/Strategy: "1"
    RGBD/NeighborLinkRefining: "true"
    RGBD/ProximityBySpace: "true"
    RGBD/AngularUpdate: "0.05"
    RGBD/LinearUpdate: "0.05"
    RGBD/CreateOccupancyGrid: "true"
    Grid/3D: "false"
    Grid/RayTracing: "true"
    Grid/RangeMax: "2.5"
    Grid/CellSize: "0.05"
    Grid/MinClusterSize: "30"
    Grid/MaxGroundHeight: "0.15"
    Grid/MinObstacleHeight: "0.03"
    Mem/IncrementalMemory: "true"
    Mem/InitWMWithAllNodes: "false"
    Optimizer/GravitySigma: "0.3"
